Bdk send
BitcoinDevShop/mutiny-web-poc pull request #11
Opened 2022-10-26 22:34 UTC by futurepaul

2022-10-26 23:29 UTC, benthecarman requested changes

2022-10-26 23:29 UTC, benthecarman commented on node-manager/src/wallet.rs
> +                .fee_rate(FeeRate::from_sat_per_vb(5.0));
should make fee rate a param here

2022-10-26 23:29 UTC, benthecarman commented on node-manager/src/nodemanager.rs
> +    pub async fn send_to_address(&self, destination_address: String, amount: u64) -> String {
should make fee an optional param here as well, and if it is `None` we can get the free rate from esplora

2022-10-26 23:29 UTC, benthecarman commented on node-manager/src/wallet.rs
> +                .do_not_spend_change()
i dont see the need for this for now

2022-10-26 23:35 UTC, TonyGiorgio approved these changes

2022-10-27 01:16 UTC, benthecarman approved these changes

2022-10-27 01:16 UTC, merged