add proxy and esplora to environment
BitcoinDevShop/mutiny-web-poc pull request #155
Opened 2022-12-02 22:50 UTC by futurepaul

2022-12-03 22:37 UTC, futurepaul commented
![Screen Shot 2022-12-03 at 4 22 11 PM](https://user-images.githubusercontent.com/543668/205464524-e80c9efd-9bbe-41a4-8752-8c491edd9073.png)

2022-12-04 00:02 UTC, benthecarman commented on frontend/src/routes/Settings.tsx
> +                    })
we still need to call localStorage.clear(); here

2022-12-05 15:14 UTC, TonyGiorgio requested changes

2022-12-06 01:28 UTC, futurepaul commented on node-manager/src/ldkstorage.rs
> +        user_esplora_url: Option<String>,
made an issue https://github.com/BitcoinDevShop/mutiny-web-poc/issues/170

2022-12-06 01:45 UTC, merged